### ISSUE TITLE
giving back to open source

### ISSUE THREAD

**Issue by filtercake** [filtercake/orga#45]
![image](https://cloud.githubusercontent.com/assets/170145/8330321/e8436a74-1a80-11e5-86d7-b0ef5163e791.png)

**Comment by filtercake** [comment]
https://github.com/Dogfalo/materialize/issues/1580

**Comment by rafszul** [comment]
https://github.com/Dogfalo/materialize/issues/1580#issuecomment-116197875 

i would suppose there is somwhere a repo or a collection of references to deliberations on this kind of typical and inevitable questions that come to mind when working with open src. projects

keep up good work

**Comment by filtercake** [comment]
@rafszul thx, the notification of your comment must have slipped through, sorry :/

it was the first time i heard sb phrase it like that and just wanted to document it here. i have some future efforts in mind to raise awareness in companies how much they benefit from open-source code and the community at large. it's not just that they don't send back some of the money via donations – they actually think they are entitled to free maintenance, too?

currently though i am doing more research like the stuff in #33, so this topic will have to wait...
